repos:
- repo: https://github.com/digitalpulp/pre-commit-php.git
  rev: 1.4.0
  hooks:
  - id: php-unit
- repo: https://github.com/digitalpulp/pre-commit-php.git
  rev: 1.4.0
  hooks:
  - id: php-lint
- repo: local
  hooks:
  - id: phpcs
    name: phpcs
    language: system
    entry: phpcs --standard=phpcs.xml.dist