<?php
	/**
	* The core controller which subcontrollers should extend upon.
	* @author Allan Thue Rehhoff
	*/
	abstract class Controller {

		/**
		* @var Holds the current application instance.
		*/
		protected $application;

		/**
		* @var Holds the \Document instance
		*/
		protected $document;

		/**
		* @var Path to the current view that should be displayed.
		*/
		protected $view;

		/**
		* @var $_GET and $_POST merged together.
		*/
		protected $request;

		/**
		* @var Page title to be displayed
		*/
		protected $title;

		/**
		* @var Variable data generated by extending controllers.
		*/
		protected $data = [];

		/**
		* @var The current them instance.
		*/
		public $theme;

		/**
		* @var Child controllers to be executed when the main one finalizes.
		*/
		protected $children = [];

		/**
		* Child controllers should declare this function instead of a constructor.
		*/
		abstract protected function index();

		/**
		* Constructs the overall environment, setting up helpers and initial variables.
		* By making this final child controllers don't need to call parent::__construct().
		* @uses \Registry
		* @uses \Document
		* @uses \Core\Theme
		* @return void
		*/
		final public function __construct() {
			$this->initialize();
		}

		/**
		* Boots up constructor and controller variables.
		* @return void
		*/
		final public function initialize() : void {
			$this->configuration = Registry::get("Core\Configuration");
			$this->application 	 = Registry::get("Core\Application");
			$this->database 	 = Registry::get("Database\Connection");
			$this->request 		 = $_GET + $_POST;
			$this->view 		 = $this->application->arg(0);

			$this->setTitle(array_slice($this->application->getArgs(), -1)[0]);

			$this->document = Registry::set(new \Document);
			$this->theme = Registry::set(new \Core\Theme($this->configuration->get("theme")));
		}

		/**
		* Contains accessible theme variables.
		* @uses \Document
		* @return void
		*/
		final public function finalize() : void {
			$this->data["header"] = $this->getView("header");
			$this->data["footer"] = $this->getView("footer");

			$this->data["current"] = $this->application->arg(0);

			$this->data["stylesheets"] = $this->document->getStylesheets();
			$this->data["javascript"]  = $this->document->getJavascript("footer");

			foreach($this->children as $child) {
				$this->application->executeController($child);
			}
		}

		/**
		* Provides data set by extending controllers.
		* @return array
		*/
		final public function getData() : array {
			return $this->data;
		}

		/**
		* Set a dynamic value for the title tag.
		* @param (string) $title a title to display in a template file.
		* @return void
		*/
		final public function setTitle(string $title) : void {
			$this->data["title"] = sprintf($this->configuration->get("base_title"), $title);
		}

		/**
		* Get the current page title to be displayed.
		* @return string
		*/
		final public function getTitle() : string {
			return $this->data["title"];
		}

		/**
		* Get the path to a template file, ommit .tpl.php extension
		* @param (string) $template name of the template file to get path for,
		* @return string
		*/
		final public function getView(string $template = null) : string {
			if($template === null) {
				$template = $this->view;
			}

			$view = $this->theme->getTemplatePath($template.".tpl.php");

			if(is_file($view) === false) {
				throw new Exception("View template file '".$template.".tpl.php' not found in theme.");
			}

			return $view;
		}

		/**
		* Checks if the requested controller has a corresponding view.
		* @return bool
		*/
		final public function hasView() : bool {
			return file_exists($this->getView()) && !CLI;
		}

		/**
		* Convenience wrapper, for setting/overriding a view within any controller
		* @param Name of the view to use, without .tpl.php extensions.
		* @return bool
		*/
		final protected function setView(string $view) : void {
			$this->view = $view;

			if($this->application->getControllerPath($view) !== null) {
				$this->children[] = ucfirst($view);
			}
		}
	}